language: cpp
sudo: true
compiler:
- gcc
os:
- linux
before_install:
- unset CXX
- unset CC
script: bash build.sh
env:
  global:
    secure: "uZblq1VGKre+crMm/bNkvJYQNyYUOGRuUsxYpkZrqhWYFvEEAbr3RVkjNTy+7xjBtGDBgKisUWpnYy9tNZfenLe4ZacLbi3X9z675AVhPt83LS7zuMyTvi2hAMjFv08CoGLnRB1giPcVuE0MNnQx0AxALg2JvGPsECjezD/8KSgY8atfA6JhLaWCrO0NmmfgmvAWINLGLF/nNbRBb9PudlLaon7MZOOz2faU2I1DhlNNCtZQdTcFEEcg4iS2xlXQ4vCM9scEdW4C7ZQO4ztyFHV3gtXoiCYu7a0p7sKsEiPEjhhfBDT4H/OIBenICWN3uPwY/Qx6dj/ePtb9IzDUrpJ5TnuKlse6mHbDJk9d2xsXyIaURAnu7V/aEWHkSFCeFWojH0wFiO9t37rkDMWoVsWZe6QSbCZurNzORiC6Bg8fdU+54gDWGf/PPPKOXxBs1sPIQLPatdGUjGGoiCB/L3I8skRo5LKuL7ywGH/kk7N1wysBS5W0gRvk3lmOkRJ4U8FVe89CvrkXhT2zeFsweAi6TQUeeD8setA5Z1P4OMX9tB0D3xbczz36X8oERKzlHNzNeQtvPO/SPVnXmCOzZL4qkfY1l3lVLHC9VvtcCpL7AbzcZ61SuUgSg6GdiWZ0FadWHHv7oP07JwJbYBeZ5sOiuulXs40WvyIMSwymXqg="
after_success:
  - .travis/github-mirror.sh "vsimon/webrtcbuilds" `cat out/revision_number` out/src
  - .travis/github-release.sh "vsimon/webrtcbuilds" `cat out/revision_number` out/*.zip
